# Attempted Merge

Because the kaggle dataset has two advantages that the new dataset doesn't have it would be advantages to merge the two datasets.
The first advantage is that the players are already sperated into player 1 and player 2 so for the testing and training it would not be neccessary to split the new dataset.
The second advantage is that the kaggle dataset has an easy usable Score, since the new dataset has a score column with many other variables like () and ! that give more detail to the score, but make the score column not easily transformable.

The following notebook shows that the is not mergeable since the datacolumns are too diffrent.
To merge them we need on the one hand the Tournament or date of the match and the Name of both players or their Rank.
The problem with the name or rank is, that the Ranks of the 2 datasets don't match up, which indicades that the Rank is entered at diffrent times(before and after a game or before and after a tournament).
The Name column is a smaller problem since it in both entries, but both use diffrent naming conventions. So to merge them we reduce both to just the last name.
The problem to merge the entries is the tournament or date on the name. The problem with the tournament is that both datasets also use diffrent naming conventions, which makes this column unusable.
So the last column to try and merge the names is the date entry, since both date entries are now in the same format the assumption was that both of them use the same date for the matches.
However the manual looking at the unmerged table based on the column commondate shows that both datasets use anothe format again.

Since the merging is not easily possible and only around 17095 entries could be merged for an reliable result the dataset with more features should be used.

In [69]:
import pandas as pd

csv1 = pd.read_csv("BearbTennis.csv")
csv2 = pd.read_csv("Tml_2000_2026.csv")


csv1["Date"] = csv1["Date"].astype(str)
csv2["tourney_date"] = csv2["tourney_date"].astype(str)

csv1["WinRank"] = pd.to_numeric(csv1["WinRank"], errors="coerce")
csv2["winner_rank"] = pd.to_numeric(csv2["winner_rank"], errors="coerce")

csv1["LosRank"] = pd.to_numeric(csv1["LosRank"], errors="coerce")
csv2["loser_rank"] = pd.to_numeric(csv2["loser_rank"], errors="coerce")

csv1 = csv1.dropna(subset=["WinRank", "LosRank"])
csv2 = csv2.dropna(subset=["winner_rank", "loser_rank"])

csv1["WinRank"] = csv1["WinRank"].astype(int)
csv1["LosRank"] = csv1["LosRank"].astype(int)

csv2["winner_rank"] = csv2["winner_rank"].astype(int)
csv2["loser_rank"] = csv2["loser_rank"].astype(int)

merged = pd.merge(
    csv1,
    csv2,
    left_on=["Date", "WinRank", "LosRank"],
    right_on=["tourney_date", "winner_rank", "loser_rank"],
    how="inner"
)

C:\Users\timst\AppData\Local\Temp\ipykernel_17988\3688843450.py:3: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  csv1 = pd.read_csv("BearbTennis.csv")
C:\Users\timst\AppData\Local\Temp\ipykernel_17988\3688843450.py:4: DtypeWarning: Columns (3,6,7,9,13,15,16,17,19,23,25,26,27,29,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  csv2 = pd.read_csv("Tml_2000_2026.csv")

In [70]:
merged

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,...,2.0,2.0,1.0,57.0,35.0,23.0,8.0,9.0,3.0,7.0
1,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3,Arthurs W.,Gambill J.M.,Gambill J.M.,...,1.0,26.0,2.0,103.0,59.0,49.0,22.0,16.0,4.0,5.0
2,Qatar Open,20000103,International,Outdoor,Hard,1st Round,3,Puerta M.,Mirnyi M.,Mirnyi M.,...,4.0,2.0,1.0,58.0,43.0,25.0,10.0,10.0,6.0,9.0
3,Qatar Open,20000103,International,Outdoor,Hard,Quarterfinals,3,El Aynaoui Y.,Tillstrom M.,El Aynaoui Y.,...,8.0,2.0,4.0,96.0,61.0,40.0,17.0,13.0,7.0,10.0
4,Qatar Open,20000103,International,Outdoor,Hard,Quarterfinals,3,Schalken S.,Kiefer N.,Kiefer N.,...,4.0,1.0,2.0,40.0,27.0,11.0,5.0,6.0,5.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17090,Grand Prix Hassan II,20260404,ATP250,Outdoor,Clay,Semifinals,3,Jodar R.,Ugo Carabelli C.,Jodar R.,...,2,3,0,44,27,19,3,7,4,8
17091,Tiriac Open,20260404,ATP250,Outdoor,Clay,Semifinals,3,Van De Zandschulp B.,Navone M.,Navone M.,...,14,0,2,115,76,46,21,18,7,13
17092,U.S.Men's Clay Court Championships,20260405,ATP250,Outdoor,Clay,The Final,3,Paul T.,Burruchaga R.,Paul T.,...,12,1,3,106,78,41,19,14,11,16
17093,Tiriac Open,20260405,ATP250,Outdoor,Clay,The Final,3,Merida Aguilar D.,Navone M.,Navone M.,...,8,0,2,87,60,31,11,15,6,14
17094,Grand Prix Hassan II,20260405,ATP250,Outdoor,Clay,The Final,3,Trungelliti M.,Jodar R.,Jodar R.,...,1,2,4,60,37,24,7,9,5,9

In [71]:
merged.describe()

,Best of,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Scorelength,Matches,Diff,1WinB,2WinB,1LoseB,2LoseB,match_id,WinRank,LosRank,winner_rank,loser_rank
count,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000,17095.000000
mean,3.445042,85.012284,85.276982,454.913016,462.449371,1.768433,9.610588,2.652647,0.008774,35.092425,35.959520,28.177186,28.332085,22150.283592,68.170518,102.118748,68.170518,102.118748
std,0.831903,106.264626,102.017617,923.005714,1008.595826,2.531744,3.170505,0.792626,5.843433,53.098450,55.402121,31.538676,31.734367,21614.606224,74.255049,124.938836,74.255049,124.938836
min,3.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,7.000000,2.000000,-16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,3.000000,33.000000,33.000000,-1.000000,-1.000000,1.170000,7.000000,2.000000,-5.000000,6.000000,6.000000,7.000000,7.000000,4509.500000,25.000000,43.000000,25.000000,43.000000
50%,3.000000,61.000000,63.000000,-1.000000,-1.000000,1.610000,7.000000,2.000000,0.000000,17.000000,17.000000,18.000000,17.000000,10080.000000,52.000000,73.000000,52.000000,73.000000
75%,3.000000,100.000000,101.000000,705.000000,694.000000,2.370000,11.000000,3.000000,5.000000,41.000000,42.000000,36.000000,36.000000,40291.000000,87.000000,113.000000,87.000000,113.000000
max,5.000000,2159.000000,1690.000000,16790.000000,16950.000000,67.000000,19.000000,5.000000,17.000000,555.000000,584.000000,228.000000,224.000000,67352.000000,1277.000000,2159.000000,1277.000000,2159.000000

In [72]:
mergedTest = pd.merge(
    csv1,
    csv2,
    left_on=["Date", "WinRank", "LosRank"],
    right_on=["tourney_date", "winner_rank", "loser_rank"],
    how="outer",
    indicator=True
)

In [73]:
mergedTest["commonDate"] = mergedTest["Date"].combine_first(mergedTest["tourney_date"])

In [74]:
mergedTest

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,...,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,_merge,commonDate
0,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Dosedel S.,Ljubicic I.,Dosedel S.,...,1.0,57.0,35.0,23.0,8.0,9.0,3.0,7.0,both,20000103
1,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,2nd Round,3.0,Hewitt L.,Petrovic D.,Hewitt L.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
2,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Clement A.,Enqvist T.,Enqvist T.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
3,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Escude N.,Baccanello P.,Escude N.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
4,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Knippschild J.,Federer R.,Federer R.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,53,33,13,9,8,4,10,right_only,20260410
127283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,87,42,28,22,14,6,10,right_only,20260410
127284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,54,32,14,12,9,0,4,right_only,20260411
127285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,59,40,28,9,10,1,4,right_only,20260411
127286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,92,53,31,22,10,8,11,right_only,20260412

In [75]:
not_merged_csv1 = mergedTest[mergedTest["_merge"] == "left_only"]

In [76]:
not_merged_csv2 = mergedTest[mergedTest["_merge"] == "right_only"]

In [77]:
not_merged_all = mergedTest[mergedTest["_merge"] != "both"]
not_merged_all.sort_values("commonDate")

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,...,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,_merge,commonDate
1,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,2nd Round,3.0,Hewitt L.,Petrovic D.,Hewitt L.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
67419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,70.0,37.0,26.0,15.0,10.0,4.0,7.0,right_only,20000103
67418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,66.0,26.0,17.0,24.0,11.0,0.0,3.0,right_only,20000103
67417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,52.0,23.0,15.0,15.0,9.0,3.0,6.0,right_only,20000103
67416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,61.0,21.0,14.0,23.0,9.0,2.0,4.0,right_only,20000103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,97,63,43,19,16,3,7,right_only,20260410
127283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,87,42,28,22,14,6,10,right_only,20260410
127285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,59,40,28,9,10,1,4,right_only,20260411
127284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,54,32,14,12,9,0,4,right_only,20260411
127286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,92,53,31,22,10,8,11,right_only,20260412

In [78]:
df_one_per_date_csv1 = not_merged_csv1.sort_values("Date").groupby("Date").first().reset_index()

In [79]:
not_merged_all.head(80)

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,...,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,_merge,commonDate
1,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,2nd Round,3.0,Hewitt L.,Petrovic D.,Hewitt L.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
2,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Clement A.,Enqvist T.,Enqvist T.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
3,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Escude N.,Baccanello P.,Escude N.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
4,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Knippschild J.,Federer R.,Federer R.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
5,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Fromberg R.,Woodbridge T.,Fromberg R.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,Qatar Open,20000103,International,Outdoor,Hard,2nd Round,3.0,Marin J.A.,Mirnyi M.,Mirnyi M.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
79,Qatar Open,20000103,International,Outdoor,Hard,2nd Round,3.0,Santoro F.,van Lottum J.,Santoro F.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
80,Qatar Open,20000103,International,Outdoor,Hard,1st Round,3.0,Tillstrom M.,Ivanisevic G.,Tillstrom M.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
81,Qatar Open,20000103,International,Outdoor,Hard,2nd Round,3.0,Schuettler R.,Vacek D.,Schuettler R.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
82,Qatar Open,20000103,International,Outdoor,Hard,2nd Round,3.0,Cherkasov A.,Tillstrom M.,Tillstrom M.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103

In [80]:
df_one_per_date_csv1 = not_merged_csv1.sort_values("Date").groupby("Date").first().reset_index()
df_one_per_date_csv1

,Date,Tournament,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,...,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,_merge,commonDate
0,20000103,Australian Hardcourt Championships,International,Outdoor,Hard,2nd Round,3.0,Hewitt L.,Petrovic D.,Hewitt L.,...,None,None,None,None,None,None,None,None,left_only,20000103
1,20000214,Kroger St. Jude,International Gold,Indoor,Hard,1st Round,3.0,Jensen L.,Mamiit C.,Mamiit C.,...,None,None,None,None,None,None,None,None,left_only,20000214
2,20000228,Citrix Tennis Championships,International,Outdoor,Hard,1st Round,3.0,Roddick A.,Tieleman L.,Tieleman L.,...,None,None,None,None,None,None,None,None,left_only,20000228
3,20000306,Colombia Open,International,Outdoor,Clay,1st Round,3.0,Hadad M.,Hantschk M.,Hantschk M.,...,None,None,None,None,None,None,None,None,left_only,20000306
4,20000323,Ericsson Open,Masters,Outdoor,Hard,2nd Round,3.0,Chang M.,Rios M.,Rios M.,...,None,None,None,None,None,None,None,None,left_only,20000323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5916,20260331,Grand Prix Hassan II,ATP250,Outdoor,Clay,1st Round,3.0,Skatov T.,Ugo Carabelli C.,Ugo Carabelli C.,...,None,None,None,None,None,None,None,None,left_only,20260331
5917,20260401,U.S.Men's Clay Court Championships,ATP250,Outdoor,Clay,2nd Round,3.0,McDonald M.,Tirante T.A.,Tirante T.A.,...,None,None,None,None,None,None,None,None,left_only,20260401
5918,20260402,U.S.Men's Clay Court Championships,ATP250,Outdoor,Clay,2nd Round,3.0,Burruchaga R.,Nakashima B.,Burruchaga R.,...,None,None,None,None,None,None,None,None,left_only,20260402
5919,20260403,U.S.Men's Clay Court Championships,ATP250,Outdoor,Clay,Quarterfinals,3.0,Burruchaga R.,Tien L.,Burruchaga R.,...,None,None,None,None,None,None,None,None,left_only,20260403
5920,20260404,U.S.Men's Clay Court Championships,ATP250,Outdoor,Clay,Semifinals,3.0,Burruchaga R.,Tirante T.A.,Burruchaga R.,...,None,None,None,None,None,None,None,None,left_only,20260404

In [81]:
list1 =not_merged_csv1["Tournament"].unique()
print(list1.tolist())

['Australian Hardcourt Championships', 'Gold Flake Open', 'Qatar Open', 'Kroger St. Jude', 'Citrix Tennis Championships', 'Colombia Open', 'Ericsson Open', 'Mallorca Open', 'Heineken Trophy', 'Dutch Open', 'Croatia Open', 'Dubai Championships', 'Franklin Templeton Tennis Classic', 'Stella Artois', 'Generali Open', 'Brasil Open', 'Heineken Open', 'Salem Open', 'TATA Open', 'Bellsouth Open', 'Estoril Open', 'BMW Open', 'Gerry Weber Open', 'Ordina Open', 'Cincinnati TMS', 'TD Waterhouse Cup', 'AAPT Championships', 'Qatar Exxon Mobil Open', 'adidas International', 'Australian Open', 'Breil ATP', 'Siebel Open', 'Open 13', 'ABN AMRO World Tennis Tournament', 'Copa AT&T', 'Abierto Mexicano', 'Copenhagen Open', 'International Championships', 'Pacific Life Open', 'NASDAQ-100 Open', 'Grand Prix Hassan II', 'Monte Carlo Masters', 'Open Seat Godo', "U.S. Men's Clay Court Championships", 'CAM Open Comunidad Valenciana', 'Telecom Italia Masters Roma', 'Hamburg TMS', 'Internationaler Raiffeisen Grand Prix', 'French Open', 'Nottingham Open', 'Wimbledon', 'Swedish Open', 'Hall of Fame Championships', 'Allianz Suisse Open', 'Priority Telecom Dutch Open', 'Mercedes Cup', 'RCA Championships', 'Mercedes-Benz Cup', 'Legg Mason Classic', 'Idea Prokom Open', 'Montreal TMS', 'Western & Southern Financial Group Masters', 'US Open', 'Open Romania', 'Campionati Internazionali Di Sicilia', 'Thailand Open', 'Japan Open', 'Kremlin Cup', 'Open de Moselle', 'Grand Prix de Lyon', 'CA Tennis Trophy', 'Madrid Masters', 'Stockholm Open', 'Swiss Indoors', 'St. Petersburg Open', 'BNP Paribas', 'Masters Cup', 'Indesit ATP Milano Indoor ', 'ATP Buenos Aires 2004', 'Toronto TMS', 'China Open', 'Next Generation Hardcourts', 'Medibank International', 'Internazionali di Lombardia', 'ATP Buenos Aires 2005', 'SAP Open', 'Regions Morgan Keegan Championships', "Dubai Duty Free Men's Open", 'Channel Open', 'Open de Tenis Comunidad Valenciana', 'Rogers Cup', 'Pilot Pen Tennis', 'Vietnam Open', 'BA-CA Tennis Trophy', 'Davidoff Swiss Indoors', 'Next Generation Adelaide International', 'Chennai Open', 'Sydney International', 'Movistar Open', 'PBZ Zagreb Indoors', 'Copa Telmex', 'Dubai Tennis Championships', "Campionati Internazional d'Italia", 'Hypo Group Tennis International', 'Red Letter Days Open', 'Synsam Swedish Open', 'Countrywide Classic', 'Rogers Masters', 'Kingfisher Airlines Tennis Open', 'Sony Ericsson Open', "Internazionali BNL d'Italia", 'The Nottingham Open', 'Catella Swedish Open', 'Indianapolis Tennis Championships', 'Austrian Open', 'AIG Japan Open Tennis Championships', 'Open Sabadell Atlántico 2008', 'Orange Prokom Open', 'Slazenger Open', 'Studena Croatia Open', 'Brisbane International', 'SA Tennis Open', 'BNP Paribas Open', 'Open Banco Sabadell', 'Serbia Open', 'Mutua Madrileña Madrid Open', 'AEGON Championships', 'AEGON International', 'International German Open', 'LA Tennis Open', 'Proton Malaysian Open', 'Rakuten Japan Open Tennis Championships', 'Shanghai Masters', 'Valencia Open 500', 'BNP Paribas Masters', 'Open de Nice Côte d’Azur', 'Unicef Open', 'SkiStar Swedish Open', 'German Open Tennis Championships', 'Atlanta Tennis Championships', 'Farmers Classic', 'Open Sud de France', 'Copa Claro', 'Bet-At-Home Cup', 'Winston-Salem Open at Wake Forest University', 'Malaysian Open', 'Erste Bank Open', 'Apia International', 'VTR Open', 'BRD Nastase Tiriac Trophy', 'Mutua Madrid Open', 'ATP Vegeta Croatia Open', 'Crédit Agricole Suisse Open Gstaad', 'BB&T Atlanta Open', 'Citi Open', 'U.S. National Indoor Tennis Championships', 'Portugal Open', 'Power Horse Cup', 'Topshelf Open', 'Claro Open Colombia', 'Royal Guard Open Chile', 'Rio Open', 'Delray Beach Open', 'Dusseldorf Open', 'bet-at-home Open', 'Shenzhen Open', 'Ecuador Open', 'Memphis Open', 'Argentina Open', 'Istanbul Open', 'Millenium Estoril Open', 'Geneva Open', 'AEGON Open', 'Konzum Croatia Open', 'Suisse Open Gstaad', 'ASB Classic', 'Garanti Koza Sofia Open', 'German Tennis Championships', 'Abierto Mexicano Mifel', 'Chengdu Open', 'European Open', 'Open Banco Sabadell ', 'Gazprom Hungarian Open', 'Lyon Open', 'Ricoh Open', 'Antalya Open', 'Tata Open', 'New York Open', 'Millennium Estoril Open', 'Eastbourne International', 'Maharashtra Open', 'Sofia Open', 'Cordoba Open', 'Hungarian Open', 'Rosmalen Grass Court Championships', 'Halle Open', "Queen's Club Championships", 'Zhuhai Open', 'Adelaide International', 'Chile Open', 'Forte Village Sardegna Open', 'bett1HULKS Indoors', 'bett1HULKS Championship', 'Astana Open', 'Great Ocean Road Open', 'Murray River Open', 'Singapore Open', 'Miami Open', 'Sardegna Open', 'AnyTech365 Andalucia Open', 'Barcelona Open', 'Belgrade Open', 'Emilia-Romagna Open', 'Mallorca Championships', 'Viking International', 'Nordea Open', 'Mifel Open', 'Canadian Open', 'San Diego Open', 'Vienna Open', 'Adelaide International 1', 'Melbourne Summer Set', 'Adelaide International 2', 'Sydney Tennis Classic', 'Dallas Open', 'Atlanta Open', 'Los Cabos Open', 'Tel Aviv Open', 'Korea Open', 'Gijon Open', 'Firenze Open', 'Napoli Cup', 'Srpska Open', 'Stuttgart Open', 'Zhuhai Championships', 'Japan Open Tennis Championships', 'Nordic Open', 'Hong Kong Tennis Open', 'Tiriac Open', 'Hangzhou Open', 'Almaty Open', "U.S.Men's Clay Court Championships", 'Hamburg Open', 'Hellenic Championship']

In [82]:
df_one_per_date_csv2 = not_merged_csv2.sort_values("tourney_date").groupby("tourney_date").first().reset_index()
df_one_per_date_csv2[["tourney_id","tourney_name","surface","tourney_level","tourney_date","match_num","winner_id","winner_name","winner_rank","winner_rank_points","loser_id","loser_name","loser_age","loser_rank"]]

,tourney_id,tourney_name,surface,tourney_level,tourney_date,match_num,winner_id,winner_name,winner_rank,winner_rank_points,loser_id,loser_name,loser_age,loser_rank
0,2000-7308,Adelaide,Hard,250,20000103,1,E113,Thomas Enqvist,4.0,2606.0,C487,Arnaud Clement,22.045,56.0
1,2000-301,Auckland,Hard,250,20000110,26,C274,Michael Chang,50.0,722.0,G182,Magnus Gustafsson,33.018,60.0
2,2000-580,Australian Open,Hard,G,20000117,119,E121,Younes El Aynaoui,29.0,991.0,C487,Arnaud Clement,22.084,54.0
3,2000-D074,Davis Cup G2 QF: HKG vs PAK,Hard,D,20000128,2,Q019,Aisam-Ul-Haq Qureshi,301.0,100.0,W270,Wayne Wong,18.856,1298.0
4,2000-D072,Davis Cup WG R1: ESP vs ITA,Clay,D,20000204,3,G254,Andrea Gaudenzi,90.0,444.0,C378,Albert Costa,24.613,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1246,2026-410,Monte Carlo,Clay,M,20260408,41,HB71,Hubert Hurkacz,74.0,745,M0CI,Fabian Marozsan,26.5,43.0
1247,2026-410,Monte Carlo,Clay,M,20260409,49,DH58,Alex de Minaur,6.0,4095,B0PG,Alexander Blockx,21.002,91.0
1248,2026-410,Monte Carlo,Clay,M,20260410,50,Z355,Alexander Zverev,3.0,5205,F0FV,Joao Fonseca,19.636,40.0
1249,2026-410,Monte Carlo,Clay,M,20260411,55,A0E2,Carlos Alcaraz,1.0,13590,VA25,Valentin Vacherot,27.4,23.0
1250,2026-410,Monte Carlo,Clay,M,20260412,56,S0AG,Jannik Sinner,2.0,12400,A0E2,Carlos Alcaraz,22.938,1.0

In [83]:
list2 =not_merged_csv2["tourney_name"].unique()
print(list2.tolist())

['Adelaide', 'Doha', 'Chennai', 'Auckland', 'Australian Open', 'Davis Cup G1 QF: CHN vs UZB', 'Davis Cup G2 QF: HKG vs PAK', 'Davis Cup WG R1: SUI vs AUS', 'Davis Cup WG R1: SVK vs AUT', 'Davis Cup G1 QF: PER vs BAH', 'Davis Cup WG R1: RUS vs BEL', 'Davis Cup WG R1: BRA vs FRA', 'Davis Cup G1 QF: CHI vs CAN', 'Davis Cup G1 QF: COL vs ECU', 'Davis Cup G2 QF: CRC vs MEX', 'Davis Cup WG R1: CZE vs GBR', 'Davis Cup WG R1: ESP vs ITA', 'Davis Cup WG R1: GER vs NED', 'Davis Cup G1 QF: IND vs LIB', 'Davis Cup G1 QF: JPN vs KOR', 'Davis Cup G2 QF: KAZ vs TPE', 'Davis Cup G1 QF: NZL vs THA', 'Davis Cup G1 R1: UKR vs POR', 'Davis Cup G2 QF: VEN vs URU', 'Davis Cup WG R1: ZIM vs USA', 'Marseille', 'Memphis', 'Mexico City', 'Delray Beach', 'Santiago', 'Scottsdale', 'Miami Masters', 'Davis Cup G1 SF: PER vs ECU', 'Davis Cup WG QF: USA vs CZE', 'Davis Cup WG QF: ESP vs RUS', 'Davis Cup WG QF: BRA vs SVK', 'Davis Cup WG QF: AUS vs GER', 'Davis Cup G2 SF: VEN vs PAR', 'Davis Cup G2 SF: GUA vs MEX', 'Davis Cup G1 SF: CHI vs ARG', 'Davis Cup G1 SF: UZB vs NZL', 'Davis Cup G1 SF: IND vs KOR', 'Davis Cup G1 QF: FIN vs SWE', 'Davis Cup G1 QF: ROU vs HUN', 'Davis Cup G1 QF: BLR vs RSA', 'Davis Cup G1 QF: MAR vs UKR', 'Davis Cup G1 PO: CHN vs THA', 'Davis Cup G1 PO: JPN vs LIB', 'Davis Cup G2 PO: CRC vs CUB', 'Davis Cup G2 SF: TPE vs PAK', 'Davis Cup G2 PO: HKG vs KAZ', 'Casablanca', 'Atlanta', 'Monte Carlo Masters', 'Barcelona', 'Davis Cup G2 R1: LUX vs IRL', 'Davis Cup G2 R1: TUR vs DEN', 'Davis Cup G2 R1: LTU vs CIV', 'Davis Cup G2 R1: EGY vs SLO', 'Davis Cup G2 R1: POL vs EST', 'Davis Cup G2 R1: BUL vs GRE', 'Davis Cup G2 R1: NOR vs ISR', 'Munich', 'Rome Masters', 'World Team Cup', 'St. Poelten', 'Roland Garros', "Queen's Club", 'Nottingham', 'Wimbledon', 'Gstaad', 'Newport', 'Davis Cup WG SF: AUS vs BRA', 'Davis Cup G2 QF: IRL vs CRO', 'Davis Cup WG PO: GBR vs ECU', 'Davis Cup WG PO: UZB vs NED', 'Davis Cup WG PO: ZIM vs ROU', 'Stuttgart Outdoor', 'Davis Cup WG SF: ESP vs USA', 'Davis Cup G1 PO: CAN vs ARG', 'Davis Cup G1 PO: BAH vs COL', 'Davis Cup G2 F: MEX vs VEN', 'Davis Cup G2 QF: DEN vs CIV', 'Davis Cup G2 QF: POL vs SLO', 'Davis Cup G2 QF: GRE vs NOR', 'Davis Cup G2 PO: TUR vs LTU', 'Davis Cup G2 PO: BUL vs ISR', 'Davis Cup WG PO: FRA vs AUT', 'Davis Cup WG PO: ITA vs BEL', 'Davis Cup WG PO: SWE vs IND', 'Davis Cup WG PO: SUI vs BLR', 'Kitzbuhel', 'Los Angeles', 'San Marino', 'Canada Masters', 'Cincinnati Masters', 'Indianapolis', 'Long Island', 'US Open', 'Tashkent', 'Bucharest', 'Sydney Olympics', 'Palermo', 'Davis Cup G1 PO: LIB vs CHN', 'Davis Cup G1 PO: COL vs ARG', 'Davis Cup G2 F: INA vs TPE', 'Davis Cup G2 SF: CRO vs CIV', 'Davis Cup G2 SF: GRE vs SLO', 'Davis Cup G1 PO: FIN vs HUN', 'Davis Cup G1 PO: POR vs RSA', 'Tokyo', 'Vienna', 'Toulouse', 'Shanghai', 'Moscow', 'Stuttgart Masters', 'Lyon', 'Paris Masters', 'Stockholm', 'Brighton', 'Davis Cup WG F: ESP vs AUS', 'Sydney', 'Bogota', 'Milan', 'Davis Cup WG R1: AUS vs ECU', 'Davis Cup WG R1: BRA vs MAR', 'Davis Cup WG R1: SWE vs CZE', 'Davis Cup WG R1: SVK vs RUS', 'Davis Cup WG R1: BEL vs FRA', 'Davis Cup WG R1: SUI vs USA', 'Davis Cup WG R1: GER vs ROU', 'Davis Cup WG R1: NED vs ESP', 'Davis Cup G1 R1: POR vs UKR', 'Davis Cup G1 R1: FIN vs SLO', 'Davis Cup G1 QF: ARG vs MEX', 'Davis Cup G1 QF: BAH vs PER', 'Davis Cup G1 QF: INA vs UZB', 'Davis Cup G1 QF: KOR vs NZL', 'Davis Cup G1 QF: JPN vs THA', 'Davis Cup G1 QF: CHN vs IND', 'Davis Cup G2 QF: URU vs COL', 'Davis Cup G2 QF: CRC vs AHO', 'Davis Cup G2 QF: PAR vs VEN', 'Davis Cup G2 QF: TPE vs PAK', 'Copenhagen', 'Vina del Mar', 'Buenos Aires', 'San Jose', 'Dubai', 'Acapulco', 'Indian Wells Masters', 'Davis Cup G1 SF: ARG vs CAN', 'Davis Cup G1 SF: BAH vs CHI', 'Davis Cup G1 QF: GBR vs POR', 'Davis Cup G1 QF: CRO vs AUT', 'Davis Cup G1 QF: BLR vs ZIM', 'Davis Cup G1 QF: FIN vs ITA', 'Davis Cup G2 SF: URU vs AHO', 'Davis Cup G2 SF: GUA vs VEN', 'Davis Cup G2 SF: LIB vs HKG', 'Davis Cup G1 SF: NZL vs UZB', 'Davis Cup G1 SF: JPN vs IND', 'Davis Cup G1 PO: KOR vs INA', 'Davis Cup G1 PO: THA vs CHN', 'Davis Cup G2 PO: COL vs CRC', 'Davis Cup WG QF: BRA vs AUS', 'Davis Cup WG QF: SWE vs RUS', 'Davis Cup WG QF: SUI vs FRA', 'Davis Cup WG QF: NED vs GER', 'Estoril', 'Davis Cup G2 R1: HUN vs MON', 'Davis Cup G2 R1: IRL vs DEN', 'Davis Cup G2 R1: TUR vs GRE', 'Davis Cup G2 R1: LUX vs CIV', 'Davis Cup G2 R1: POL vs ISR', 'Davis Cup G2 R1: RSA vs YUG', 'Mallorca', 'Hamburg Masters', "'s-Hertogenbosch", 'Stuttgart', 'Umag', 'Davis Cup G2 QF: DEN vs HUN', 'Davis Cup G2 QF: GRE vs ARM', 'Davis Cup G2 QF: LUX vs NOR', 'Davis Cup G2 QF: ISR vs RSA', 'Davis Cup G2 PO: MON vs IRL', 'Davis Cup G2 PO: MDA vs TUR', 'Davis Cup G2 PO: CIV vs EST', 'Davis Cup G2 PO: YUG vs POL', 'Davis Cup G2 F: URU vs VEN', 'Davis Cup G1 PO: MEX vs CAN', 'Sopot', 'Washington', 'Davis Cup G1 PO: MEX vs PER', 'Davis Cup G2 SF: GRE vs DEN', 'Davis Cup G2 SF: LUX vs ISR', 'Davis Cup WG SF: AUS vs SWE', 'Davis Cup WG SF: NED vs FRA', 'Davis Cup WG PO: ARG vs BLR', 'Davis Cup WG PO: BEL vs MAR', 'Davis Cup WG PO: CZE vs ROU', 'Davis Cup WG PO: ECU vs GBR', 'Davis Cup WG PO: ITA vs CRO', 'Davis Cup WG PO: SVK vs CHI', 'Davis Cup WG PO: ESP vs UZB', 'Davis Cup G1 PO: INA vs CHN', 'Davis Cup G1 PO: AUT vs UKR', 'Davis Cup G1 PO: ZIM vs SLO', 'Hong Kong', 'Davis Cup WG PO: USA vs IND', 'Basel', 'Davis Cup WG F: AUS vs FRA', 'Davis Cup WG R1: FRA vs NED', 'Davis Cup WG R1: CZE vs BRA', 'Davis Cup WG R1: ESP vs MAR', 'Davis Cup WG R1: USA vs SVK', 'Davis Cup WG R1: RUS vs SUI', 'Davis Cup WG R1: GBR vs SWE', 'Davis Cup WG R1: CRO vs GER', 'Davis Cup WG R1: ARG vs AUS', 'Davis Cup G1 R1: ZIM vs POR', 'Davis Cup G1 R1: AUT vs ISR', 'Davis Cup G1 QF: THA vs UZB', 'Davis Cup G1 QF: KOR vs JPN', 'Davis Cup G1 QF: NZL vs INA', 'Davis Cup G2 QF: CHN vs KUW', 'Davis Cup G2 QF: KAZ vs PHI', 'Davis Cup G2 QF: HKG vs TPE', 'Davis Cup G1 QF: BAH vs VEN', 'Davis Cup G1 QF: CAN vs MEX', 'Davis Cup G2 QF: GUA vs PER', 'Davis Cup G2 QF: COL vs CUB', 'Davis Cup G2 QF: TRI vs URU', 'Rotterdam', 'Davis Cup G2 SF: CHN vs KAZ', 'Davis Cup G2 SF: PAK vs TPE', 'Davis Cup G1 SF: THA vs JPN', 'Davis Cup G1 SF: NZL vs IND', 'Davis Cup G1 QF: ITA vs FIN', 'Davis Cup G1 QF: ZIM vs BLR', 'Davis Cup G1 QF: ROU vs AUT', 'Davis Cup G1 QF: BEL vs GRE', 'Davis Cup WG QF: FRA vs CZE', 'Davis Cup WG QF: USA vs ESP', 'Davis Cup WG QF: RUS vs SWE', 'Davis Cup WG QF: ARG vs CRO', 'Davis Cup G1 SF: VEN vs ECU', 'Davis Cup G1 SF: CAN vs CHI', 'Davis Cup G2 SF: PAR vs PER', 'Davis Cup G2 SF: COL vs URU', 'Davis Cup G2 PO: GUA vs AHO', 'Davis Cup G2 PO: CUB vs TRI', 'Davis Cup G1 PO: UZB vs KOR', 'Davis Cup G2 R1: UKR vs BUL', 'Davis Cup G2 R1: NOR vs EGY', 'Davis Cup G2 R1: YUG vs RSA', 'Davis Cup G2 R1: LUX vs HUN', 'Davis Cup G2 R1: SLO vs GHA', 'Halle', 'Davis Cup G2 F: URU vs PER', 'Davis Cup G2 QF: CIV vs BUL', 'Davis Cup G2 QF: DEN vs NOR', 'Davis Cup G2 QF: LUX vs YUG', 'Davis Cup G2 QF: SLO vs IRL', 'Davis Cup G1 PO: BLR vs POR', 'Davis Cup G1 PO: MEX vs CHI', 'Davis Cup G2 PO: EGY vs MDA', 'Davis Cup G2 PO: RSA vs HUN', 'Amersfoort', 'Costa do Sauipe', 'Davis Cup G2 F: PAK vs CHN', 'Davis Cup WG SF: FRA vs USA', 'Davis Cup WG SF: RUS vs ARG', 'Davis Cup WG PO: AUS vs IND', 'Davis Cup WG PO: ZIM vs BEL', 'Davis Cup WG PO: BRA vs CAN', 'Davis Cup WG PO: GER vs VEN', 'Davis Cup WG PO: GBR vs THA', 'Davis Cup WG PO: FIN vs NED', 'Davis Cup WG PO: SVK vs ROU', 'Davis Cup WG PO: MAR vs SUI', 'Davis Cup G1 PO: BAH vs MEX', 'Davis Cup G2 SF: NOR vs CIV', 'Davis Cup G2 SF: LUX vs SLO', 'Davis Cup G1 PO: ITA vs POR', 'Davis Cup G1 PO: ISR vs GRE', 'Madrid Masters', 'Davis Cup WG F: FRA vs RUS', 'Davis Cup WG R1: ROU vs FRA', 'Davis Cup WG R1: NED vs SUI', 'Davis Cup WG R1: AUS vs GBR', 'Davis Cup WG R1: SWE vs BRA', 'Davis Cup WG R1: CRO vs USA', 'Davis Cup WG R1: ESP vs BEL', 'Davis Cup WG R1: ARG vs GER', 'Davis Cup WG R1: CZE vs RUS', 'Davis Cup G1 R1: ECU vs CHI', 'Davis Cup G1 R1: IND vs JPN', 'Davis Cup G1 R1: NZL vs PAK', 'Davis Cup G1 R1: UZB vs INA', 'Davis Cup G1 R1: THA vs KOR', 'Davis Cup G1 R1: NOR vs AUT', 'Davis Cup G1 R1: BLR vs ISR', 'Davis Cup G2 R1: CUB vs COL', 'Davis Cup G2 R1: URU vs DOM', 'Davis Cup G2 R1: TPE vs KAZ', 'Davis Cup G2 R1: POR vs MON', 'Davis Cup G2 R1: RSA vs POL', 'Davis Cup G2 R1: GHA vs SLO', 'Davis Cup G2 R1: DEN vs TUN', 'Davis Cup G2 R1: BUL vs UKR', 'Davis Cup G2 R1: YUG vs CIV', 'Davis Cup G2 R1: IRL vs EGY', 'Davis Cup G2 R1: AND vs GRE', 'Davis Cup WG QF: FRA vs SUI', 'Davis Cup WG QF: SWE vs AUS', 'Davis Cup WG QF: ESP vs CRO', 'Davis Cup WG QF: ARG vs RUS', 'Davis Cup G1 R2: ECU vs VEN', 'Davis Cup G1 R2: CAN vs PER', 'Davis Cup G1 R2: IND vs NZL', 'Davis Cup G1 R2: UZB vs THA', 'Davis Cup G1 R2: LUX vs SVK', 'Davis Cup G1 R2: AUT vs FIN', 'Davis Cup G1 R2: BLR vs ZIM', 'Davis Cup G1 R2: MAR vs ITA', 'Davis Cup G2 R2: PAR vs MEX', 'Davis Cup G2 R2: DOM vs CUB', 'Davis Cup G2 R2: CHN vs TPE', 'Davis Cup G2 PO: AHO vs HAI', 'Davis Cup G2 PO: URU vs COL', 'Davis Cup G1 PO: INA vs KOR', 'Houston', 'Valencia', 'World Team Championship', 'Bastad', 'Davis Cup G2 R2: RSA vs POR', 'Davis Cup G2 R2: DEN vs SLO', 'Davis Cup G2 R2: YUG vs BUL', 'Davis Cup G2 R2: GRE vs IRL', 'Davis Cup G2 PO: POL vs MON', 'Davis Cup G2 PO: UKR vs CIV', 'Davis Cup G2 PO: AND vs EGY', 'Davis Cup G1 PO: VEN vs CHI', 'Davis Cup G1 PO: NOR vs FIN', 'Davis Cup G1 PO: ISR vs ZIM', 'Davis Cup WG SF: AUS vs SUI', 'Davis Cup WG SF: ESP vs ARG', 'Davis Cup G2 F: DOM vs PAR', 'Davis Cup G2 F: TPE vs HKG', 'Davis Cup G2 R3: DEN vs RSA', 'Davis Cup G2 R3: GRE vs YUG', 'Davis Cup G1 PO: PAK vs KOR', 'Davis Cup G1 PO: NOR vs LUX', 'Davis Cup G1 PO: ZIM vs ITA', 'Davis Cup WG PO: AUT vs BEL', 'Davis Cup WG PO: CAN vs BRA', 'Davis Cup WG PO: THA vs CZE', 'Davis Cup WG PO: GER vs BLR', 'Davis Cup WG PO: MAR vs GBR', 'Davis Cup WG PO: NED vs IND', 'Davis Cup WG PO: ECU vs ROU', 'Davis Cup WG PO: SVK vs USA', 'Bangkok', 'Metz', 'St. Petersburg', 'Masters Cup', 'Davis Cup WG F: AUS vs ESP', 'Davis Cup WG R1: AUS vs SWE', 'Davis Cup WG R1: USA vs AUT', 'Davis Cup WG R1: BLR vs RUS', 'Davis Cup WG R1: MAR vs ARG', 'Davis Cup WG R1: ROU vs SUI', 'Davis Cup WG R1: FRA vs CRO', 'Davis Cup WG R1: NED vs CAN', 'Davis Cup WG R1: CZE vs ESP', 'Davis Cup G1 R1: LUX vs FIN', 'Davis Cup G1 R1: ZIM vs GRE', 'Davis Cup G1 R1: VEN vs PAR', 'Davis Cup G1 R1: PER vs CHI', 'Davis Cup G1 R1: TPE vs UZB', 'Davis Cup G1 R1: INA vs JPN', 'Davis Cup G1 R1: NZL vs IND', 'Davis Cup G2 R1: JAM vs MEX', 'Davis Cup G2 R1: MAS vs KOR', 'Davis Cup G2 R1: LIB vs IRI', 'Davis Cup G2 R1: HKG vs KUW', 'Davis Cup WG QF: USA vs SWE', 'Davis Cup WG QF: BLR vs ARG', 'Davis Cup WG QF: ESP vs NED', 'Davis Cup G1 R2: GER vs ISR', 'Davis Cup G1 R2: LUX vs GBR', 'Davis Cup G1 R2: BEL vs ZIM', 'Davis Cup G1 R2: RSA vs SVK', 'Davis Cup G1 R2: BRA vs PAR', 'Davis Cup G1 R2: CHI vs ECU', 'Davis Cup G1 R2: THA vs UZB', 'Davis Cup G1 R2: JPN vs IND', 'Davis Cup G1 PO: INA vs NZL', 'Davis Cup G2 R1: ITA vs GEO', 'Davis Cup G2 R1: BUL vs EGY', 'Davis Cup G2 R1: SLO vs POL', 'Davis Cup G2 R1: TUN vs POR', 'Davis Cup G2 R1: SCG vs LAT', 'Davis Cup G2 R1: IRL vs HUN', 'Davis Cup G2 R1: NOR vs UKR', 'Davis Cup G2 R2: DOM vs URU', 'Davis Cup G2 R2: KOR vs LIB', 'Davis Cup G2 R2: CHN vs KUW', 'Davis Cup G2 PO: PUR vs JAM', 'Davis Cup G2 PO: IRI vs MAS', 'Davis Cup G1 PO: VEN vs BRA', 'Davis Cup G2 R2: ITA vs BUL', 'Davis Cup G2 R2: POL vs ALG', 'Davis Cup G2 R2: POR vs SCG', 'Davis Cup G2 R2: HUN vs NOR', 'Davis Cup G2 PO: GEO vs EGY', 'Davis Cup G2 PO: LAT vs TUN', 'Davis Cup G2 PO: UKR vs IRL', 'Athens Olympics', 'Beijing', 'Davis Cup G1 PO: ISR vs FIN', 'Davis Cup WG SF: USA vs BLR', 'Davis Cup WG SF: ESP vs FRA', 'Davis Cup G1 PO: RSA vs GRE', 'Davis Cup G1 PO: BRA vs PER', 'Davis Cup G1 PO: PAK vs NZL', 'Davis Cup G2 F: ITA vs POL', 'Davis Cup G2 F: HUN vs SCG', 'Davis Cup G2 F: MEX vs DOM', 'Davis Cup G2 F: CHN vs KOR', 'Davis Cup WG PO: AUS vs MAR', 'Davis Cup WG PO: CHI vs JPN', 'Davis Cup WG PO: CRO vs BEL', 'Davis Cup WG PO: PAR vs CZE', 'Davis Cup WG PO: SVK vs GER', 'Davis Cup WG PO: AUT vs GBR', 'Davis Cup WG PO: ROU vs CAN', 'Davis Cup WG PO: RUS vs THA', 'Davis Cup WG F: ESP vs USA', 'Davis Cup WG R1: SVK vs ESP', 'Davis Cup WG R1: SUI vs NED', 'Davis Cup WG R1: AUS vs AUT', 'Davis Cup WG R1: ARG vs CZE', 'Davis Cup WG R1: RUS vs CHI', 'Davis Cup WG R1: FRA vs SWE', 'Davis Cup WG R1: ROU vs BLR', 'Davis Cup WG R1: USA vs CRO', 'Davis Cup G1 R1: VEN vs PER', 'Davis Cup G1 R1: MEX vs ECU', 'Davis Cup G1 R1: SCG vs ZIM', 'Davis Cup G1 R1: LUX vs ITA', 'Davis Cup G1 R2: ISR vs GBR', 'Davis Cup G1 R2: RSA vs GER', 'Davis Cup G1 R1: PAK vs THA', 'Davis Cup G1 R1: TPE vs JPN', 'Davis Cup G1 R1: INA vs UZB', 'Davis Cup G1 R1: IND vs CHN', 'Davis Cup G2 R1: GHA vs FIN', 'Davis Cup G2 R1: BUL vs GEO', 'Davis Cup G2 R1: UKR vs NOR', 'Davis Cup G2 R1: EST vs POR', 'Davis Cup G2 R1: ALG vs POL', 'Davis Cup G2 R1: SLO vs CIV', 'Davis Cup G2 R1: LAT vs GRE', 'Davis Cup G2 R1: COL vs BRA', 'Davis Cup G2 R1: AHO vs BAH', 'Davis Cup G2 R1: CUB vs URU', 'Davis Cup G2 R1: JAM vs DOM', 'Davis Cup G2 R1: NZL vs KAZ', 'Davis Cup G2 R1: IRI vs KUW', 'Davis Cup G2 R1: PHI vs KOR', 'Davis Cup G1 R2: ITA vs MAR', 'Davis Cup G1 R2: VEN vs CAN', 'Davis Cup G1 R2: SCG vs BEL', 'Davis Cup G1 R2: PAK vs TPE', 'Davis Cup G1 R2: IND vs UZB', 'Davis Cup WG QF: SVK vs NED', 'Davis Cup WG QF: AUS vs ARG', 'Davis Cup WG QF: RUS vs FRA', 'Davis Cup WG QF: CRO vs ROU', 'Davis Cup G1 PO: LUX vs MAR', 'Davis Cup G1 PO: JPN vs THA', 'Davis Cup G1 PO: CHN vs INA', 'Davis Cup G2 R2: FIN vs BUL', 'Davis Cup G2 R2: UKR vs HUN', 'Davis Cup G2 R2: POR vs ALG', 'Davis Cup G2 R2: SLO vs LAT', 'Davis Cup G2 PO: GHA vs GEO', 'Davis Cup G2 PO: NOR vs MON', 'Davis Cup G2 PO: POL vs EST', 'Davis Cup G2 PO: GRE vs CIV', 'Davis Cup G2 R2: URU vs DOM', 'Davis Cup G2 PO: COL vs BAH', 'Davis Cup G2 PO: JAM vs CUB', 'Davis Cup G2 R2: NZL vs KUW', 'Davis Cup G2 PO: IRI vs KAZ', 'Davis Cup G2 PO: LIB vs PHI', 'New Haven', 'Davis Cup WG SF: SVK vs ARG', 'Davis Cup WG SF: CRO vs RUS', 'Davis Cup WG PO: AUT vs ECU', 'Davis Cup WG PO: CAN vs BLR', 'Davis Cup WG PO: CHI vs PAK', 'Davis Cup WG PO: CZE vs GER', 'Davis Cup WG PO: ITA vs ESP', 'Davis Cup WG PO: IND vs SWE', 'Davis Cup WG PO: SUI vs GBR', 'Davis Cup WG PO: BEL vs USA', 'Davis Cup G1 PO: ZIM vs ISR', 'Davis Cup G1 PO: MAR vs RSA', 'Davis Cup G1 PO: THA vs INA', 'Davis Cup G2 F: UKR vs BUL', 'Davis Cup G2 F: POR vs SLO', 'Davis Cup G2 F: NZL vs KOR', 'Davis Cup G2 F: URU vs BRA', 'Ho Chi Minh City', 'Davis Cup WG F: SVK vs CRO', 'Zagreb', 'Davis Cup WG R1: AUT vs CRO', 'Davis Cup WG R1: ARG vs SWE', 'Davis Cup WG R1: BLR vs ESP', 'Davis Cup WG R1: GER vs FRA', 'Davis Cup WG R1: NED vs RUS', 'Davis Cup WG R1: USA vs ROU', 'Davis Cup WG R1: CHI vs SVK', 'Davis Cup G1 R1: PER vs BRA', 'Davis Cup G1 R1: VEN vs MEX', 'Davis Cup G1 R1: KOR vs IND', 'Davis Cup G1 R1: TPE vs PAK', 'Davis Cup G1 R1: JPN vs CHN', 'Davis Cup G1 R1: UZB vs THA', 'Davis Cup G1 R1: LUX vs POR', 'Davis Cup G1 R1: ISR vs SCG', 'Davis Cup G2 R1: COL vs URU', 'Davis Cup G2 R1: AHO vs GUA', 'Davis Cup G2 R1: NZL vs LIB', 'Davis Cup G2 R1: KUW vs KAZ', 'Las Vegas', 'Davis Cup WG QF: CRO vs ARG', 'Davis Cup WG QF: AUS vs BLR', 'Davis Cup WG QF: FRA vs RUS', 'Davis Cup WG QF: USA vs CHI', 'Davis Cup G1 R2: ECU vs BRA', 'Davis Cup G1 R2: MEX vs CAN', 'Davis Cup G1 R2: TPE vs KOR', 'Davis Cup G1 R2: THA vs JPN', 'Davis Cup G1 PO: IND vs PAK', 'Davis Cup G1 PO: UZB vs CHN', 'Davis Cup G1 R2: MAR vs CZE', 'Davis Cup G1 R2: ITA vs LUX', 'Davis Cup G1 R2: GBR vs SCG', 'Davis Cup G1 R2: UKR vs BEL', 'Davis Cup G2 R2: COL vs PAR', 'Davis Cup G2 R2: AHO vs DOM', 'Davis Cup G2 PO: URU vs BOL', 'Davis Cup G2 PO: JAM vs GUA', 'Davis Cup G2 R2: KAZ vs NZL', 'Davis Cup G2 R2: INA vs HKG', 'Davis Cup G2 R1: ZIM vs NOR', 'Davis Cup G2 R1: GRE vs MKD', 'Davis Cup G2 R1: FIN vs IRL', 'Davis Cup G2 R1: ALG vs SLO', 'Davis Cup G2 R1: HUN vs EGY', 'Davis Cup G2 R1: BUL vs CYP', 'Davis Cup G2 R1: POL vs LAT', 'Davis Cup G2 R1: GEO vs RSA', 'Poertschach', 'Davis Cup G1 PO: PER vs ECU', 'Davis Cup G1 PO: CAN vs VEN', 'Davis Cup G1 PO: GBR vs ISR', 'Davis Cup G2 R2: NOR vs MKD', 'Davis Cup G2 R2: FIN vs ALG', 'Davis Cup G2 R2: BUL vs HUN', 'Davis Cup G2 R2: POL vs GEO', 'Davis Cup G2 PO: GRE vs ZIM', 'Davis Cup G2 PO: IRL vs SLO', 'Davis Cup G2 PO: EGY vs CYP', 'Davis Cup G2 PO: LAT vs RSA', 'Davis Cup WG SF: ARG vs AUS', 'Davis Cup WG SF: RUS vs USA', 'Davis Cup WG PO: AUT vs MEX', 'Davis Cup WG PO: GER vs THA', 'Davis Cup WG PO: NED vs CZE', 'Davis Cup WG PO: ROU vs KOR', 'Davis Cup WG PO: SVK vs BEL', 'Davis Cup WG PO: ESP vs ITA', 'Davis Cup WG PO: BRA vs SWE', 'Davis Cup WG PO: SUI vs SCG', 'Davis Cup G1 PO: VEN vs ECU', 'Davis Cup G1 PO: CHN vs PAK', 'Davis Cup G1 PO: MAR vs POR', 'Davis Cup G1 PO: UKR vs GBR', 'Davis Cup G2 F: DOM vs COL', 'Davis Cup G2 F: KAZ vs INA', 'Davis Cup G2 F: MKD vs FIN', 'Davis Cup G2 F: HUN vs GEO', 'Mumbai', 'Davis Cup WG F: RUS vs ARG', 'Davis Cup WG R1: CHI vs RUS', 'Davis Cup WG R1: FRA vs ROU', 'Davis Cup WG R1: GER vs CRO', 'Davis Cup WG R1: BEL vs AUS', 'Davis Cup WG R1: CZE vs USA', 'Davis Cup WG R1: SUI vs ESP', 'Davis Cup WG R1: BLR vs SWE', 'Davis Cup WG R1: AUT vs ARG', 'Davis Cup G1 R1: PER vs VEN', 'Davis Cup G1 R1: CAN vs COL', 'Davis Cup G1 R1: TPE vs THA', 'Davis Cup G1 R1: CHN vs JPN', 'Davis Cup G1 R1: UZB vs IND', 'Davis Cup G1 R1: KOR vs KAZ', 'Davis Cup G1 R1: ISR vs LUX', 'Davis Cup G1 R1: GEO vs POR', 'Davis Cup G2 R1: ECU vs AHO', 'Davis Cup G2 R1: DOM vs ESA', 'Davis Cup G2 R1: PHI vs PAK', 'Davis Cup G2 R1: KUW vs IRI', 'Davis Cup G2 R1: HKG vs INA', 'Davis Cup WG QF: BEL vs GER', 'Davis Cup WG QF: SWE vs ARG', 'Davis Cup G1 R2: PER vs MEX', 'Davis Cup G1 R2: BRA vs CAN', 'Davis Cup G1 R2: JPN vs THA', 'Davis Cup G1 R2: KOR vs UZB', 'Davis Cup G1 PO: TPE vs CHN', 'Davis Cup G1 PO: KAZ vs IND', 'Davis Cup G1 R2: MKD vs SVK', 'Davis Cup G1 R2: ISR vs ITA', 'Davis Cup G1 R2: SRB vs GEO', 'Davis Cup G1 R2: GBR vs NED', 'Davis Cup G2 R2: URU vs ECU', 'Davis Cup G2 R2: PAR vs DOM', 'Davis Cup G2 PO: ESA vs CUB', 'Davis Cup G2 R2: NZL vs PHI', 'Davis Cup G2 R2: KUW vs INA', 'Davis Cup G2 PO: IRI vs HKG', 'Davis Cup G2 R1: MAR vs DEN', 'Davis Cup G2 R1: EST vs SLO', 'Davis Cup G2 R1: GRE vs UKR', 'Davis Cup G2 R1: NGR vs POL', 'Davis Cup G2 R1: LAT vs BUL', 'Davis Cup G2 R1: CYP vs FIN', 'Davis Cup G2 R1: ALG vs MON', 'Davis Cup G2 R1: NOR vs HUN', 'Davis Cup G1 PO: MEX vs VEN', 'Davis Cup G1 PO: ITA vs LUX', 'Davis Cup G2 R2: SLO vs MAR', 'Davis Cup G2 R2: GRE vs POL', 'Davis Cup G2 R2: FIN vs LAT', 'Davis Cup G2 R2: HUN vs MON', 'Davis Cup G2 PO: DEN vs EST', 'Davis Cup G2 PO: NGR vs UKR', 'Davis Cup G2 PO: CYP vs BUL', 'Davis Cup G2 PO: NOR vs ALG', 'Davis Cup WG PO: ISR vs CHI', 'Davis Cup WG PO: SRB vs AUS', 'Davis Cup WG PO: AUT vs BRA', 'Davis Cup WG PO: PER vs BLR', 'Davis Cup WG PO: GBR vs CRO', 'Davis Cup WG PO: CZE vs SUI', 'Davis Cup WG PO: JPN vs ROU', 'Davis Cup WG PO: SVK vs KOR', 'Davis Cup WG SF: RUS vs GER', 'Davis Cup WG SF: SWE vs USA', 'Davis Cup G1 PO: VEN vs COL', 'Davis Cup G1 PO: KAZ vs CHN', 'Davis Cup G1 PO: MKD vs LUX', 'Davis Cup G1 PO: NED vs POR', 'Davis Cup G2 F: PAR vs URU', 'Davis Cup G2 F: KUW vs PHI', 'Davis Cup G2 F: POL vs MAR', 'Davis Cup G2 F: LAT vs MON', 'Davis Cup WG F: USA vs RUS', 'Davis Cup G1 R1: TPE vs AUS', 'Davis Cup G1 R1: KAZ vs THA', 'Davis Cup G1 R1: IND vs UZB', 'Davis Cup G1 R1: PHI vs JPN', 'Davis Cup G1 R1: CAN vs MEX', 'Davis Cup G1 R1: URU vs COL', 'Davis Cup G1 R1: MKD vs LAT', 'Davis Cup G1 R1: SUI vs POL', 'Davis Cup G2 R1: CHN vs LIB', 'Davis Cup G2 R1: INA vs HKG', 'Davis Cup G2 R1: AHO vs ECU', 'Davis Cup G2 R1: BOL vs DOM', 'Davis Cup G2 R1: BAH vs VEN', 'Davis Cup G2 R1: PAR vs ESA', 'Davis Cup WG R1: RUS vs SRB', 'Davis Cup WG R1: CZE vs BEL', 'Davis Cup WG R1: ARG vs GBR', 'Davis Cup WG R1: ISR vs SWE', 'Davis Cup WG R1: GER vs KOR', 'Davis Cup WG R1: PER vs ESP', 'Davis Cup WG R1: AUT vs USA', 'Da

In [84]:
mergedT = mergedTest.sort_values("commonDate").groupby("commonDate").first().reset_index()
mergedT

,commonDate,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,...,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,_merge
0,20000103,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Dosedel S.,Ljubicic I.,...,2.0,1.0,57.0,35.0,23.0,8.0,9.0,3.0,7.0,both
1,20000110,Heineken Open,20000110,International,Outdoor,Hard,2nd Round,3.0,Rosset M.,van Lottum J.,...,2.0,3.0,47.0,24.0,14.0,10.0,8.0,2.0,6.0,both
2,20000117,Australian Open,20000117,Grand Slam,Outdoor,Hard,1st Round,5.0,Pioline C.,Ivanisevic G.,...,26.0,8.0,148.0,90.0,69.0,36.0,27.0,5.0,8.0,both
3,20000128,None,None,None,None,None,None,NaN,None,None,...,None,None,None,None,None,None,None,None,None,right_only
4,20000204,None,None,None,None,None,None,NaN,None,None,...,None,None,None,None,None,None,None,None,None,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6821,20260408,None,None,None,None,None,None,NaN,None,None,...,0,2,60,34,18,14,8,5,8,right_only
6822,20260409,None,None,None,None,None,None,NaN,None,None,...,1,1,75,45,36,14,12,1,3,right_only
6823,20260410,None,None,None,None,None,None,NaN,None,None,...,4,2,97,63,43,19,16,3,7,right_only
6824,20260411,None,None,None,None,None,None,NaN,None,None,...,3,1,59,40,28,9,10,1,4,right_only
6825,20260412,None,None,None,None,None,None,NaN,None,None,...,3,5,92,53,31,22,10,8,11,right_only

In [85]:
list3 =merged["Tournament"].unique()
print(list3.tolist())

['Australian Hardcourt Championships', 'Qatar Open', 'Heineken Open', 'Sydney International', 'Australian Open', 'Dubai Open', 'Marseille Open', 'Sybase Open', 'Kroger St. Jude', 'ABN AMRO World Tennis Tournament', 'AXA Cup', 'Mexican Open', 'Copenhagen Open', 'Citrix Tennis Championships', 'Chevrolet Cup', 'Colombia Open', 'Franklin Templeton Tennis Classic', 'Indian Wells TMS', 'Grand Prix Hassan II', 'Galleryfurniture.com Tennis Challenge', 'Estoril Open', 'Monte Carlo Masters', 'Open Seat Godo', 'Mallorca Open', 'BMW Open', 'U.S. Clay Court Championships', 'Rome TMS', 'Hamburg TMS', 'Internationaler Raiffeisen Grand Prix', 'French Open', 'Gerry Weber Open', 'Stella Artois', 'Nottingham Open', 'Heineken Trophy', 'Wimbledon', 'Swedish Open', 'Gstaad Open', 'Hall of Fame Championships', 'Dutch Open', 'Mercedes Cup', 'Croatia Open', 'Generali Open', 'Mercedes-Benz Cup', "Tennis Int'l of San Marino", 'Toronto TMS', 'Cincinnati TMS', 'RCA Championships', 'Legg Mason Classic', 'The Hamlet Cup', 'US Open', 'Open Romania', "President's Cup", 'Campionati Internazionali Di Sicilia', 'Salem Open', 'Japan Open', 'CA Tennis Trophy', 'Heineken Open Shanghai', 'adidas Open', 'Swiss Indoors', 'Kremlin Cup', 'Stuttgart TMS', 'Grand Prix de Lyon', 'St. Petersburg Open', 'BNP Paribas', 'Samsung Open', 'Stockholm Open', 'Masters Cup', 'TATA Open', 'AAPT Championships', 'adidas International', 'Milan Indoors', 'Bellsouth Open', 'Copa AT&T', 'Abierto Mexicano', 'Dubai Championships', 'Ericsson Open', 'Verizon Tennis Challenge', "U.S. Men's Clay Court Championships", 'Idea Prokom Open', 'Montreal TMS', 'Hamlet Cup', 'Gelsor Open', 'Brasil Open', 'Pacific Life Open', 'NASDAQ-100 Open', 'Queens Club', 'Ordina Open', 'Energis Open', 'TD Waterhouse Cup', 'Madrid Masters', 'Qatar Exxon Mobil Open', 'Breil ATP', 'Open 13', 'International Championships', 'CAM Open Comunidad Valenciana', 'Telecom Italia Masters Roma', 'Allianz Suisse Open', 'Priority Telecom Dutch Open', 'Western & Southern Financial Group Masters', 'Thailand Open', 'Open de Moselle', 'Siebel Open', 'ATP Buenos Aires 2004', 'China Open', 'Next Generation Hardcourts', 'Medibank International', 'Internazionali di Lombardia', 'ATP Buenos Aires 2005', 'SAP Open', 'Regions Morgan Keegan Championships', 'Channel Open', "Dubai Duty Free Men's Open", 'Open de Tenis Comunidad Valenciana', 'Rogers Cup', 'Pilot Pen Tennis', 'Vietnam Open', 'BA-CA Tennis Trophy', 'Next Generation Adelaide International', 'Chennai Open', 'Movistar Open', 'PBZ Zagreb Indoors', 'Copa Telmex', 'Dubai Tennis Championships', "Campionati Internazional d'Italia", 'Hypo Group Tennis International', 'Red Letter Days Open', 'Synsam Swedish Open', 'Countrywide Classic', 'Rogers Masters', 'Kingfisher Airlines Tennis Open', "Internazionali BNL d'Italia", 'The Nottingham Open', 'Catella Swedish Open', 'Indianapolis Tennis Championships', 'Austrian Open', 'AIG Japan Open Tennis Championships', 'Sony Ericsson Open', 'Open Sabadell Atlántico 2008', 'Orange Prokom Open', 'Slazenger Open', 'Studena Croatia Open', 'Davidoff Swiss Indoors', 'Brisbane International', 'SA Tennis Open', 'BNP Paribas Open', 'Open Banco Sabadell', 'Mutua Madrileña Madrid Open', 'AEGON Championships', 'AEGON International', 'LA Tennis Open', 'Proton Malaysian Open', 'Rakuten Japan Open Tennis Championships', 'Shanghai Masters', 'Valencia Open 500', 'BNP Paribas Masters', 'Serbia Open', 'Open de Nice Côte d’Azur', 'Unicef Open', 'SkiStar Swedish Open', 'German Open Tennis Championships', 'Atlanta Tennis Championships', 'Farmers Classic', 'Open Sud de France', 'Copa Claro', 'Winston-Salem Open at Wake Forest University', 'Malaysian Open', 'Erste Bank Open', 'Apia International', 'VTR Open', 'BRD Nastase Tiriac Trophy', 'Mutua Madrid Open', 'ATP Vegeta Croatia Open', 'BB&T Atlanta Open', 'Crédit Agricole Suisse Open Gstaad', 'Bet-At-Home Cup', 'Citi Open', 'U.S. National Indoor Tennis Championships', 'Portugal Open', 'Power Horse Cup', 'Topshelf Open', 'Claro Open Colombia', 'Royal Guard Open Chile', 'Delray Beach Open', 'Rio Open', 'Dusseldorf Open', 'bet-at-home Open', 'Shenzhen Open', 'Memphis Open', 'Argentina Open', 'Istanbul Open', 'Millenium Estoril Open', 'Geneva Open', 'AEGON Open', 'Konzum Croatia Open', 'Suisse Open Gstaad', 'ASB Classic', 'Ecuador Open', 'Garanti Koza Sofia Open', 'German Tennis Championships', 'Chengdu Open', 'European Open', 'Open Banco Sabadell ', 'Gazprom Hungarian Open', 'Lyon Open', 'Ricoh Open', 'Antalya Open', 'Tata Open', 'New York Open', 'Millennium Estoril Open', 'Eastbourne International', 'Maharashtra Open', 'Cordoba Open', 'Sofia Open', 'Hungarian Open', 'Rosmalen Grass Court Championships', "Queen's Club Championships", 'Halle Open', 'Zhuhai Open', 'Adelaide International', 'Chile Open', 'bett1HULKS Indoors', 'Forte Village Sardegna Open', 'bett1HULKS Championship', 'Astana Open', 'Murray River Open', 'Great Ocean Road Open', 'Singapore Open', 'Sardegna Open', 'AnyTech365 Andalucia Open', 'Barcelona Open', 'Nordea Open', 'Canadian Open', 'San Diego Open', 'Vienna Open', 'Adelaide International 1', 'Adelaide International 2', 'Sydney Tennis Classic', 'Dallas Open', 'Mallorca Championships', 'Atlanta Open', 'Korea Open', 'Tel Aviv Open', 'Firenze Open', 'Gijon Open', 'Srpska Open', 'Stuttgart Open', 'Zhuhai Championships', 'Japan Open Tennis Championships', 'Nordic Open', 'Hong Kong Tennis Open', 'Los Cabos Open', 'Tiriac Open', 'Hangzhou Open', 'Almaty Open', 'Belgrade Open', "U.S.Men's Clay Court Championships", 'Hamburg Open', 'Hellenic Championship', 'Miami Open']

In [86]:
list4 =merged["tourney_name"].unique()
print(list4.tolist())

['Adelaide', 'Doha', 'Auckland', 'Sydney', 'Australian Open', 'Dubai', 'Marseille', 'San Jose', 'Memphis', 'Rotterdam', 'London', 'Mexico City', 'Copenhagen', 'Delray Beach', 'Santiago', 'Bogota', 'Scottsdale', 'Indian Wells Masters', 'Casablanca', 'Atlanta', 'Estoril', 'Monte Carlo Masters', 'Barcelona', 'Mallorca', 'Munich', 'Orlando', 'Rome Masters', 'Hamburg Masters', 'St. Poelten', 'Roland Garros', 'Halle', "Queen's Club", 'Nottingham', "'s-Hertogenbosch", 'Wimbledon', 'Bastad', 'Gstaad', 'Newport', 'Amsterdam', 'Stuttgart Outdoor', 'Umag', 'Kitzbuhel', 'Los Angeles', 'San Marino', 'Canada Masters', 'Cincinnati Masters', 'Indianapolis', 'Washington', 'Long Island', 'US Open', 'Bucharest', 'Tashkent', 'Palermo', 'Hong Kong', 'Tokyo', 'Vienna', 'Shanghai', 'Toulouse', 'Basel', 'Moscow', 'Stuttgart Masters', 'Lyon', 'St. Petersburg', 'Paris Masters', 'Brighton', 'Stockholm', 'Tennis Masters Cup', 'Chennai', 'Milan', 'Vina del Mar', 'Buenos Aires', 'Acapulco', 'Miami Masters', 'Houston', 'Stuttgart', 'Sopot', 'Salvador', 'Masters Cup', 'Amersfoort', 'Costa do Sauipe', 'Madrid Masters', 'Valencia', 'Bangkok', 'Metz', 'Beijing', 'New Haven', 'Ho Chi Minh City', 'Zagreb', 'Las Vegas', 'Poertschach', 'Mumbai', 'Warsaw', "''s-Hertogenbosch", 'Brisbane', 'Johannesburg', 'Eastbourne', 'Kuala Lumpur', 'Shanghai Masters', 'Tour Finals', 'Belgrade', 'Nice', 'Hamburg', 'Montpellier', 'Winston-Salem', 'Sao Paulo', 'Oeiras', 'Dusseldorf', 'Rio de Janeiro', 'Shenzhen', 'Istanbul', 'Geneva', 'ATP Finals', 'Quito', 'Sofia', 'Marrakech', 'Chengdu', 'Antwerp', 'Rio De Janeiro', 'Budapest', 'Antalya', 'Pune', 'New York', 'Cordoba', 'New York Open', 'Winston Salem', 'Zhuhai', 'Cologne 1', 'Sardinia', 'Cologne 2', 'Nur-Sultan', 'Murray River Open', 'Great Ocean Road Open', 'Singapore', 'Cagliari', 'Marbella', 'Serbia', 'San Diego', 'Adelaide-1', 'Adelaide-2', 'Dallas', 'Seoul', 'Tel Aviv', 'Astana', 'Florence', 'Gijon', 'Banja Luka', 'Los Cabos', 'Hangzhou', 'Almaty', 'ATP Tour Finals', 'Brussels', 'Athens']

In [87]:
mergedTest.sort_values("commonDate")

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,...,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,_merge,commonDate
0,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Dosedel S.,Ljubicic I.,Dosedel S.,...,1.0,57.0,35.0,23.0,8.0,9.0,3.0,7.0,both,20000103
67420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,80.0,35.0,27.0,18.0,11.0,11.0,15.0,right_only,20000103
67419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,70.0,37.0,26.0,15.0,10.0,4.0,7.0,right_only,20000103
67418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,66.0,26.0,17.0,24.0,11.0,0.0,3.0,right_only,20000103
67417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,52.0,23.0,15.0,15.0,9.0,3.0,6.0,right_only,20000103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,53,33,13,9,8,4,10,right_only,20260410
127283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,87,42,28,22,14,6,10,right_only,20260410
127285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,59,40,28,9,10,1,4,right_only,20260411
127284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,54,32,14,12,9,0,4,right_only,20260411
127286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,92,53,31,22,10,8,11,right_only,20260412

In [88]:
mergedTest.to_csv("MergeFail.csv", index=False)

In [89]:
mergedTest

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,...,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,_merge,commonDate
0,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Dosedel S.,Ljubicic I.,Dosedel S.,...,1.0,57.0,35.0,23.0,8.0,9.0,3.0,7.0,both,20000103
1,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,2nd Round,3.0,Hewitt L.,Petrovic D.,Hewitt L.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
2,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Clement A.,Enqvist T.,Enqvist T.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
3,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Escude N.,Baccanello P.,Escude N.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
4,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3.0,Knippschild J.,Federer R.,Federer R.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,20000103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,53,33,13,9,8,4,10,right_only,20260410
127283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,87,42,28,22,14,6,10,right_only,20260410
127284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,54,32,14,12,9,0,4,right_only,20260411
127285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,59,40,28,9,10,1,4,right_only,20260411
127286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,92,53,31,22,10,8,11,right_only,20260412

# 2nd Attempt 

We also want to try with last Names and see if this results in a better merge with more merged files

In [90]:
csv1["winner_lastA"] = csv1["Winner"].str.split().str[0]
csv1["loser_lastA"]  = csv1["Loser"].str.split().str[0]

csv2["winner_lastB"] = csv2["winner_name"].str.split().str[-1]
csv2["loser_lastB"]  = csv2["loser_name"].str.split().str[-1]

mergedLName = pd.merge(
    csv1,
    csv2,
    left_on=["Date", "winner_lastA", "loser_lastA"],
    right_on=["tourney_date", "winner_lastB", "loser_lastB"],
    how="inner",
)

In [91]:
mergedLName.describe()

,Best of,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Scorelength,Matches,Diff,1WinB,2WinB,1LoseB,2LoseB,match_id,WinRank,LosRank,winner_rank,loser_rank
count,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000,16242.000000
mean,3.439478,85.305504,85.196404,439.647396,445.741103,1.735000,9.595986,2.648996,-0.006280,34.617350,35.470940,27.760374,27.874954,21385.163096,68.445388,102.056520,68.443234,101.704839
std,0.828165,107.441444,101.407304,921.243463,992.158919,2.522788,3.150934,0.787733,5.832712,52.474922,54.703335,31.147896,31.446577,21279.602773,75.899937,124.504706,76.374630,123.488316
min,3.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,7.000000,2.000000,-16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,-1.000000,1.000000,1.000000
25%,3.000000,33.000000,33.000000,-1.000000,-1.000000,1.160000,7.000000,2.000000,-5.000000,6.000000,6.000000,7.000000,7.000000,4363.250000,25.000000,43.000000,25.000000,43.000000
50%,3.000000,61.000000,63.000000,-1.000000,-1.000000,1.600000,7.000000,2.000000,0.000000,17.000000,17.000000,17.000000,17.000000,8929.000000,52.000000,73.000000,52.000000,73.000000
75%,3.000000,100.000000,101.000000,686.000000,675.000000,2.370000,11.000000,3.000000,5.000000,40.000000,41.000000,35.000000,36.000000,38777.750000,88.000000,113.000000,88.000000,113.000000
max,5.000000,2159.000000,1690.000000,16790.000000,16950.000000,67.000000,19.000000,5.000000,17.000000,530.000000,584.000000,228.000000,224.000000,67352.000000,1277.000000,2159.000000,1466.000000,2159.000000

In [92]:
mergedLName

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,...,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_lastB,loser_lastB
0,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,...,1.0,57.0,35.0,23.0,8.0,9.0,3.0,7.0,Dosedel,Ljubicic
1,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,2nd Round,3,Hewitt L.,Petrovic D.,Hewitt L.,...,5.0,41.0,26.0,13.0,4.0,7.0,1.0,6.0,Hewitt,Petrovic
2,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Enqvist T.,...,3.0,59.0,37.0,25.0,13.0,9.0,2.0,4.0,Enqvist,Clement
3,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3,Escude N.,Baccanello P.,Escude N.,...,13.0,108.0,53.0,37.0,27.0,16.0,3.0,7.0,Escude,Baccanello
4,Australian Hardcourt Championships,20000103,International,Outdoor,Hard,1st Round,3,Knippschild J.,Federer R.,Federer R.,...,5.0,42.0,15.0,13.0,12.0,8.0,0.0,3.0,Federer,Knippschild
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16237,Tiriac Open,20260404,ATP250,Outdoor,Clay,Semifinals,3,Merida Aguilar D.,Marozsan F.,Merida Aguilar D.,...,4,84,56,36,17,14,7,12,Merida,Marozsan
16238,Grand Prix Hassan II,20260404,ATP250,Outdoor,Clay,Semifinals,3,Darderi L.,Trungelliti M.,Trungelliti M.,...,8,77,40,26,15,11,2,6,Trungelliti,Darderi
16239,U.S.Men's Clay Court Championships,20260405,ATP250,Outdoor,Clay,The Final,3,Paul T.,Burruchaga R.,Paul T.,...,3,106,78,41,19,14,11,16,Paul,Burruchaga
16240,Tiriac Open,20260405,ATP250,Outdoor,Clay,The Final,3,Merida Aguilar D.,Navone M.,Navone M.,...,2,87,60,31,11,15,6,14,Navone,Merida
16241,Grand Prix Hassan II,20260405,ATP250,Outdoor,Clay,The Final,3,Trungelliti M.,Jodar R.,Jodar R.,...,4,60,37,24,7,9,5,9,Jodar,Trungelliti

even tough we now should have more or less the same last name, it results in even less entries than the merge on the ranks